package com.example.yuvish.models.Setting

data class Filial(
    val adding_nation: Int,
    val balance: Int,
    val barcode: Int,
    val changing_coast: Int,
    val costumer_input: Int,
    val country: Country,
    val country_id: Int,
    val created_at: String,
    val filial_address: String,
    val filial_destination: String,
    val filial_director_id: Int,
    val filial_id: Int,
    val filial_name: String,
    val filial_phone: String,
    val filial_status: String,
    val filial_work_date: String,
    val landing: Int,
    val logo: String,
    val mini_logo: String,
    val mintaqa_id: Int,
    val order_brak: Int,
    val order_dog: Int,
    val send_sms: Int,
    val sizing: Int,
    val sms_coast: Int,
    val stilaj: Int,
    val to_all_drivers: Int,
    val transfer_driver: Int,
    val updated_at: String
)