package com.example.yuvish.Models.Cleaning

data class RewashReceipt(
    val brak: String,
    val called: Int,
    val ch_foiz: String,
    val ch_sum: String,
    val costumer: Costumer,
    val costumer_id: String,
    val dog: String,
    val finish_driver: Int,
    val geoplugin_latitude: String,
    val geoplugin_longitude: String,
    val izoh: String,
    val izoh2: String,
    val izoh3: String,
    val joyida: Int,
    val last_izoh: String,
    val last_izoh2: String,
    val last_operator_id: Int,
    val last_operator_id2: Int,
    val mintaqa_id: Int,
    val nomer: Int,
    val olibk_sana: String,
    val ombor_user: Int,
    val operator_id: Int,
    val order_date: String,
    val order_driver: Int,
    val order_filial_id: Int,
    val order_id: Int,
    val order_last_price: Int,
    val order_price: Int,
    val order_price_status: String,
    val order_skidka_foiz: String,
    val order_skidka_sum: String,
    val order_status: String,
    val own: Int,
    val saygak_id: Int,
    val talk_date: String,
    val talk_date2: String,
    val talk_type: String,
    val talk_type2: String,
    val tartib_raqam: Int,
    val top_sana: String,
    val topshir_sana: String
)
/*
{
    "nomer": 219,
    "order_price": 0,
    "ombor_user": 0,
    "brak": "yo`q",
    "called": 0,
    "talk_date2": "0000-00-00 00:00:00",
    "costumer_id": 407,
    "order_price_status": "none",
    "geoplugin_longitude": "none",
    "top_sana": "0000-00-00 00:00:00",
    "last_operator_id": 0,
    "mintaqa_id": 1,
    "order_filial_id": 4,
    "order_last_price": 0,
    "geoplugin_latitude": "none",
    "saygak_id": 0,
    "last_izoh": "none",
    "order_date": "2022-08-22T14:06:23",
    "order_status": "yuvilmoqda",
    "order_skidka_foiz": "none",
    "own": 0,
    "talk_type": "none",
    "olibk_sana": "0000-00-00 00:00:00",
    "operator_id": 14,
    "order_skidka_sum": "none",
    "ch_foiz": "0",
    "talk_date": "0000-00-00 00:00:00",
    "izoh": "",
    "order_driver": "0",
    "tartib_raqam": 0,
    "ch_sum": "0",
    "last_operator_id2": 0,
    "order_id": 21743,
    "izoh2": "",
    "finish_driver": 0,
    "topshir_sana": "0000-00-00",
    "joyida": 0,
    "last_izoh2": "none",
    "izoh3": "none",
    "dog": "yo`q",
    "talk_type2": "none",
    "costumer": {
      "user_id": 11,
      "costumer_source": "_",
      "millat_id": 0,
      "costumer_turi": "sifat",
      "costumer_name": "Abdusamad 555",
      "manba": "sayt",
      "id": 407,
      "costumer_phone_1": "+998986631254",
      "token": "0",
      "costumers_filial_id": 4,
      "costumer_status": "keltirish",
      "parol": "0",
      "mintaqa_id": 1,
      "costumer_phone_2": "",
      "izoh": "",
      "saygak_id": 0,
      "costumer_addres": "dqw (qdw)",
      "costumer_date": "2021-12-13T16:45:21"
    }
  },
 */