package com.example.yuvish.Models.Warehouse

data class Operator(
    val api_token: String,
    val auth_key: String,
    val balance: Int,
    val click: Int,
    val created_at: String,
    val filial_id: Int,
    val fullname: String,
    val id: Int,
    val kpi: Int,
    val maosh: Int,
    val moi_zvonki_user_name: String,
    val oylik: Int,
    val ozroq_kpi: Int,
    val password_hash: String,
    val phone: Int,
    val phone2: String,
    val plastik: Int,
    val role: String,
    val status: Int,
    val topshirish_limit: Int,
    val updated_at: String,
    val user_moi_zvonki_address: String,
    val user_moi_zvonki_api: String,
    val username: String,
    val zakaz_status: Int,
    val zayavka_limit: Int
)